"""
DESCRIPTION
-----------
shared_state provides helpers for reading/writing run-scoped shared artifacts.
Agents use this module to access the cumulative EntityRegistry snapshot generated by the orchestrator.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from src.orchestrator.artifact_store import read_json


#note: Resolve the canonical registry snapshot path for a run_id.
def registry_snapshot_path(run_id: str) -> Path:
    return Path("artifacts") / "runs" / run_id / "meta" / "entity_registry.json"


#note: Load the latest registry snapshot if it exists, otherwise return an empty dict.
def load_registry_snapshot(run_id: str) -> Dict[str, Any]:
    path = registry_snapshot_path(run_id)
    if not path.exists():
        return {}
    return read_json(path)
