#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/run_local.sh --case-file <path> [options]

Options:
  --case-file <path>       Path to the case JSON file (required).
  --pipeline-version <ver> Pipeline version override (optional).
  --run-id <id>            Run ID to use (optional; autogenerated if omitted).
  --overwrite              Replace an existing non-empty run directory.
  --backup-existing        Archive an existing non-empty run directory.
  -h, --help               Show this help message.
USAGE
}

case_file=""
pipeline_version=""
run_id=""
overwrite=false
backup_existing=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --case-file)
      case_file="${2:-}"
      shift 2
      ;;
    --pipeline-version)
      pipeline_version="${2:-}"
      shift 2
      ;;
    --run-id)
      run_id="${2:-}"
      shift 2
      ;;
    --overwrite)
      overwrite=true
      shift
      ;;
    --backup-existing)
      backup_existing=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$case_file" ]]; then
  echo "--case-file is required." >&2
  usage
  exit 1
fi

if [[ ! -f "$case_file" ]]; then
  echo "Case file not found: $case_file" >&2
  exit 1
fi

if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

if [[ -z "$run_id" ]]; then
  case_base="$(basename "$case_file")"
  case_base="${case_base%.*}"
  safe_base="$(printf '%s' "$case_base" | tr '[:space:]' '-' | tr -cd '[:alnum:]_-')"
  if [[ -z "$safe_base" ]]; then
    safe_base="run"
  fi
  timestamp="$(date -u +%Y%m%d%H%M%S)"
  run_id="local-${safe_base}-${timestamp}"
fi

cmd=(python -m src.orchestrator.run_pipeline --run-id "$run_id" --case-file "$case_file")

if [[ -n "$pipeline_version" ]]; then
  cmd+=(--pipeline-version "$pipeline_version")
fi

if [[ "$overwrite" == true ]]; then
  cmd+=(--overwrite)
elif [[ "$backup_existing" == true ]]; then
  cmd+=(--backup-existing)
fi

printf 'Running pipeline with run_id=%s\n' "$run_id"
"${cmd[@]}"
