#!/usr/bin/env pwsh
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Show-Usage {
  @"
Usage: scripts/run_local.ps1 --case-file <path> [options]

Options:
  --case-file <path>       Path to the case JSON file (required).
  --pipeline-version <ver> Pipeline version override (optional).
  --run-id <id>            Run ID to use (optional; autogenerated if omitted).
  --overwrite              Replace an existing non-empty run directory.
  --backup-existing        Archive an existing non-empty run directory.
  -h, --help               Show this help message.
"@ | Write-Output
}

$caseFile = $null
$pipelineVersion = $null
$runId = $null
$overwrite = $false
$backupExisting = $false

for ($i = 0; $i -lt $args.Count; $i++) {
  switch ($args[$i]) {
    "--case-file" {
      $i++
      if ($i -ge $args.Count) { throw "--case-file requires a value." }
      $caseFile = $args[$i]
    }
    "--pipeline-version" {
      $i++
      if ($i -ge $args.Count) { throw "--pipeline-version requires a value." }
      $pipelineVersion = $args[$i]
    }
    "--run-id" {
      $i++
      if ($i -ge $args.Count) { throw "--run-id requires a value." }
      $runId = $args[$i]
    }
    "--overwrite" { $overwrite = $true }
    "--backup-existing" { $backupExisting = $true }
    "-h" { Show-Usage; exit 0 }
    "--help" { Show-Usage; exit 0 }
    default {
      throw "Unknown argument: $($args[$i])"
    }
  }
}

if (-not $caseFile) {
  Write-Error "--case-file is required."
  Show-Usage
  exit 1
}

if (-not (Test-Path -LiteralPath $caseFile)) {
  throw "Case file not found: $caseFile"
}

if (Test-Path -LiteralPath ".env") {
  Get-Content -LiteralPath ".env" | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith("#") -or ($line -notmatch "=")) { return }
    $parts = $line.Split("=", 2)
    $name = $parts[0].Trim()
    $value = $parts[1].Trim().Trim('"')
    if ($name) {
      [Environment]::SetEnvironmentVariable($name, $value, "Process")
    }
  }
}

if (-not $runId) {
  $baseName = [System.IO.Path]::GetFileNameWithoutExtension($caseFile)
  $safeBase = ($baseName -replace "\s+", "-") -replace "[^A-Za-z0-9_-]", ""
  if (-not $safeBase) { $safeBase = "run" }
  $timestamp = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss")
  $runId = "local-$safeBase-$timestamp"
}

$cmd = @("python", "-m", "src.orchestrator.run_pipeline", "--run-id", $runId, "--case-file", $caseFile)
if ($pipelineVersion) { $cmd += @("--pipeline-version", $pipelineVersion) }
if ($overwrite) {
  $cmd += "--overwrite"
} elseif ($backupExisting) {
  $cmd += "--backup-existing"
}

Write-Output "Running pipeline with run_id=$runId"
& $cmd[0] $cmd[1..($cmd.Count - 1)]
